# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gym

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081

volumes: 
  pgdata:
